services:
  mysql-books:
    hostname: mysql
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=library
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  ms-book-1:
    image: ms-book
    ports:
      - 8090:8090
  ms-book-2:
    image: ms-book
    ports:
      - 8091:8090
